import streamlit as st

# =====================================================
# PAGE CONFIGURATION
# =====================================================

st.set_page_config(
    page_title="Pipeline Thrust Block Designer",
    page_icon="🏗",
    layout="wide"
)

# =====================================================
# HEADER
# =====================================================

col1, col2 = st.columns([6, 1])

with col1:
    st.title("🏗 Pipeline Thrust Block Designer")

with col2:
    try:
        st.image(
            "assets/logo.png",
            width=120
        )
    except:
        pass

st.caption(
    "Preliminary Engineering Design Tool for Pipeline Thrust block design"
)

# =====================================================
# WELCOME
# =====================================================

st.markdown("""
## Welcome

The **Pipeline Thrust Block Designer** has been developed to assist engineers in the
preliminary design and sizing of pipeline thrust block.

The application provides tools for:

✅ Buried Thrust Block Design

✅ SFA Chamber Thrust Block Design

✅ Hydraulic Thrust Calculations

✅ Water Hammer Consideration

✅ Soil Bearing Assessment

✅ Concrete Quantity Estimation

✅ Reinforcement Estimation

✅ Engineering Risk Assessment

✅ Design Report Generation

---

## Why Are Thrust Blocks Required?

When water flows through a pressurized pipeline and encounters a bend,
tee, reducer, valve or dead-end, an unbalanced force is generated.

This force is called:

### Hydraulic Thrust

If not restrained, hydraulic thrust may cause:

- Pipe movement
- Joint separation
- Leakage
- Structural damage
- Service interruption

Thrust blocks transfer these forces safely into:

- Surrounding soil (buried systems)

or

- Reinforced concrete structures (chambers)

---

## Available Modules

### 📚 Theory

Provides background information on:

- Hydraulic thrust
- Soil bearing capacity
- Water hammer
- Safety factors
- Concrete grades
- Design assumptions

---

### 🌍 Buried Thrust Block Designer

Used for buried pipelines where thrust is resisted by the surrounding soil.

Typical applications:

- Water transmission mains
- Distribution networks
- Buried valve chambers
- Buried bends and fittings

Features:

- Soil selection
- Water hammer factors
- Safety factors
- Automatic block sizing
- Concrete quantity estimation

---

### 🏗 SFA Chamber Thrust Block Designer

Used when thrust forces are transferred into reinforced concrete structures.

Typical applications:

- Flow meter chambers
- Valve chambers
- Pump stations
- Treatment plants

Features:

- Concrete grade selection
- Chamber dimensions
- Reinforcement estimates
- Material quantities
- Design reporting

---

### ⚠️ Risk Assessment

Provides a preliminary engineering review of:

- Pressure risk
- Soil risk
- Water hammer risk
- Safety factor adequacy
- Block size requirements

and generates engineering recommendations.
""")

# =====================================================
# DESIGN PROCESS
# =====================================================

st.markdown("""
## Typical Design Process

### Step 1 – Define Pipeline Information

Enter:

- Pipe Diameter
- Operating Pressure
- Bend Angle
- Soil Type

---

### Step 2 – Calculate Hydraulic Thrust

The application calculates the force generated by the pipeline fitting.

---

### Step 3 – Apply Design Factors

The calculation considers:

- Safety Factor
- Water Hammer Factor

to determine the Design Thrust.

---

### Step 4 – Determine Required Area

The required bearing area is calculated using:

Required Area = Design Thrust ÷ Safe Bearing Capacity

---
""")
